# Generated by Django 5.1.3 on 2024-12-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_categoryauction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.ManyToManyField(to='auctions.category'),
        ),
        migrations.DeleteModel(
            name='CategoryAuction',
        ),
    ]
