# Generated by Django 5.1.3 on 2024-12-05 22:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_watchlist"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
    ]
